name: paradoxs_coffee
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  change_app_package_name: ^1.1.0
  flutter_svg: ^2.0.6
  lottie: ^2.6.0
  flutter_carousel_widget: ^2.1.0
  zoom_tap_animation: ^1.1.0
  flutter_screenutil: ^5.9.0
  easy_localization: ^3.0.2
  shared_preferences: ^2.1.2
  url_launcher: ^6.1.11
  cached_network_image: ^3.2.3
  sqflite: ^2.3.0
  path_provider: ^2.0.15
  path: ^1.8.3
  image_picker: ^1.0.4
  mask_text_input_formatter: ^2.4.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  firebase_core: ^2.16.0
  firebase_storage: ^11.2.7
  cloud_firestore: ^4.9.2
  dio: ^5.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.6

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/images/
    - assets/svg/
    - assets/translations/


  fonts:
    - family: Sora
      fonts:
        - asset: assets/fonts/Sora/Sora-Bold.ttf
        - asset: assets/fonts/Sora/Sora-ExtraBold.ttf
        - asset: assets/fonts/Sora/Sora-ExtraLight.ttf
        - asset: assets/fonts/Sora/Sora-Light.ttf
        - asset: assets/fonts/Sora/Sora-Medium.ttf
        - asset: assets/fonts/Sora/Sora-Regular.ttf
        - asset: assets/fonts/Sora/Sora-SemiBold.ttf
        - asset: assets/fonts/Sora/Sora-Thin.ttf